// app/layout.tsx
import React from "react";
import "@/app/globals.css";
import Script from "next/script";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

declare global {
  interface Window {
    naver: any;
  }
}

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Script
          src="https://oapi.map.naver.com/openapi/v3/maps.js?ncpClientId=3e0jo40lcj"
          strategy="beforeInteractive"
        />
        <Script id="naver-map-init" strategy="afterInteractive">
          {`
            var map = null;
            function initMap() {
              if (typeof naver !== 'undefined') {
                map = new naver.maps.Map('map', {
                  center: new naver.maps.LatLng(37.3595704, 127.105399),
                  zoom: 10
                });
              }
            }
          `}
        </Script>
        {children}
      </body>
    </html>
  );
}

